/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.CSV;
import Modelo.Cliente;        
import Modelo.MetodosCliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 *
 * @author becky
 */
public class frmCliente extends javax.swing.JFrame {
    
    
    
    private CSV csv = new CSV();
    private final String fileName = "Clientes.csv";
    
   public void inicializarTablaClientes() {
        DefaultTableModel titulos = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                return false;
            }
        };

        titulos.addColumn("ID Cliente");
        titulos.addColumn("Nombre");
        titulos.addColumn("Apellido Materno");
        titulos.addColumn("Apellido Paterno");


        List<String> data = csv.obtenerDatosArchivo(fileName);
        if (data != null) {
            for (String line : data) {
                String[] row = line.split(",");
                if (row.length >= 4) {
                    Object[] fila = new Object[4];
                    fila[0] = row[0];
                    fila[1] = row[1];
                    fila[2] = row[2];
                    fila[3] = row[3];
                   
                    titulos.addRow(fila);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al leer el archivo");
        }

        tabla_consultaClientes.setModel(titulos);
        tabla_consultaClientes.setRowHeight(60);
    }
 

    public int leerIDTextField() {
        try {
            int idCliente = Integer.parseInt(texto_ID.getText().trim());
            return idCliente;
        } catch (Exception exception) {
            return -666;
        }
    }

    public String leerNombreTextField() {
        try {
            String nombre = texto_Nombre.getText().trim().replace(" ", "");
            return nombre;
        } catch (Exception exception) {
            return null;
        }
    }

    public String leerApellidoPaternoTextField() {
        try {
            String apellidoPaterno = texto_ApellidoPaterno.getText().trim().replace(" ", "");
            return apellidoPaterno;
        } catch (Exception exception) {
            return null;
        }
    }

    public String leerApellidoMaternoTextField() {
        try {
            String apellidoMaterno = texto_ApellidoMaterno.getText().trim().replace(" ", "");
            return apellidoMaterno;
        } catch (Exception exception) {
            return null;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        texto_Nombre = new javax.swing.JTextField();
        texto_ApellidoPaterno = new javax.swing.JTextField();
        texto_ApellidoMaterno = new javax.swing.JTextField();
        texto_ID = new javax.swing.JTextField();
        botonGuardarCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_consultaClientes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        botonEliminar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Datos Cliente");

        jLabel2.setText("Apellido Paterno");

        jLabel3.setText("Apellido Materno");

        jLabel4.setText("Nombre");

        jLabel5.setText("ID Cliente");

        botonGuardarCliente.setText("Guardar");
        botonGuardarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarClienteMouseClicked(evt);
            }
        });
        botonGuardarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarClienteActionPerformed(evt);
            }
        });

        tabla_consultaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido P", "Apellido M", "ID"
            }
        ));
        tabla_consultaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_consultaClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_consultaClientes);

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonEliminar.setText("Eliminar");
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(54, 54, 54))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel2)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(texto_Nombre)
                                    .addComponent(texto_ApellidoPaterno)
                                    .addComponent(texto_ApellidoMaterno)
                                    .addComponent(texto_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(94, 94, 94)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(botonGuardarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(texto_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonGuardarCliente))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_ApellidoPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(botonEliminar))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_ApellidoMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texto_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarClienteMouseClicked
    guardarCliente();
    }//GEN-LAST:event_botonGuardarClienteMouseClicked

    Cliente cliente;
    MetodosCliente metodosCliente;
  
    public void guardarCliente(){
        try {
            // que es -666
            //Cambiar el manejo de errores
            if (leerIDTextField() == -666) {
                JOptionPane.showMessageDialog(null, "Ingrese un numero entero");
            } else if (leerNombreTextField().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese el nombre");
            } else if (leerApellidoPaternoTextField().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese el apellido paterno");
            } else if (leerApellidoMaternoTextField().equals("")) {
                JOptionPane.showMessageDialog(null, "Ingrese el apellido materno");
            } else {
                cliente = new Cliente(leerNombreTextField(), leerApellidoPaternoTextField(), leerApellidoMaternoTextField(), leerIDTextField());
                if (metodosCliente.existeId(cliente.getId())) {
                    JOptionPane.showMessageDialog(null, "Este ID ya ha sido asginado");
                } else {
                    metodosCliente.agregarDatosPersona(cliente);
                    inicializarTablaClientes();
                    
                }

            }
        } catch (Exception exception) {
            System.out.println(exception);
            JOptionPane.showMessageDialog(null, "Error al guardar cliente");
        }
    }
    
    private void botonGuardarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarClienteActionPerformed
        this.guardarCliente();
    }//GEN-LAST:event_botonGuardarClienteActionPerformed

        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // noton regresar
        frmMenu regresarMenu= new frmMenu();
        regresarMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabla_consultaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_consultaClientesMouseClicked
        
        int mouseClick = tabla_consultaClientes.rowAtPoint(evt.getPoint());

        int idCliente = Integer.parseInt((String) tabla_consultaClientes.getValueAt(mouseClick, 0));
        String nombre = "" + tabla_consultaClientes.getValueAt(mouseClick, 1);
        String apellidoPaterno = "" + tabla_consultaClientes.getValueAt(mouseClick, 2);
        String apellidoMaterno = "" + tabla_consultaClientes.getValueAt(mouseClick, 3);
        
        texto_ID.setText(String.valueOf(idCliente));
        texto_Nombre.setText(nombre);
        texto_ApellidoPaterno.setText(apellidoPaterno);
        texto_ApellidoMaterno.setText(apellidoMaterno);
        
    }//GEN-LAST:event_tabla_consultaClientesMouseClicked

    public void eliminarCliente() {
        try {
            int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar al cliente?", "Aviso", 0);
            if (confirmacion == 0) {
                metodosCliente.eliminarDatosPersona(Integer.parseInt(texto_ID.getText()));
                inicializarTablaClientes();
          
            }
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, exception);
        }
    }
    
    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
    this.eliminarCliente();
    }//GEN-LAST:event_botonEliminarActionPerformed

    /*    */
    
     public frmCliente(){
        initComponents();
        setLocationRelativeTo(null);
        metodosCliente = new MetodosCliente();
        try {
            inicializarTablaClientes();
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "El archivo de texto no existe");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCliente().setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton botonEliminar;
    private javax.swing.JButton botonGuardarCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_consultaClientes;
    private javax.swing.JTextField texto_ApellidoMaterno;
    private javax.swing.JTextField texto_ApellidoPaterno;
    private javax.swing.JTextField texto_ID;
    private javax.swing.JTextField texto_Nombre;
    // End of variables declaration//GEN-END:variables
}
