/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Modelo.CSV;
import Modelo.MetodosVenta;
import Modelo.Producto;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class frmVenta extends javax.swing.JFrame {
    double precio=0;
    int cantidad=0;
    
    private final MetodosVenta metodosVenta = new MetodosVenta();
    
    DefaultTableModel modelo = new DefaultTableModel();
    ArrayList<Producto> listaProductos = new ArrayList<>();
    
    public frmVenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        DefaultComboBoxModel comboModel = new DefaultComboBoxModel (metodosVenta.getElectronicos().toArray());
        comboBoxProducto.setModel(comboModel);
        modelo.addColumn("ID PRODUCTO");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRECIO U.");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("IMPORTE");
        actualizarTabla();
        calcularPrecio();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelProducto = new javax.swing.JLabel();
        labelCantidad = new javax.swing.JLabel();
        labelPrecio = new javax.swing.JLabel();
        labelImporte = new javax.swing.JLabel();
        botonAgregar = new javax.swing.JButton();
        spinnerCantidad = new javax.swing.JSpinner();
        comboBoxProducto = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        labelIVA = new javax.swing.JLabel();
        labelSubtotal = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        labelValorSubtotal = new javax.swing.JLabel();
        labelValorIVA = new javax.swing.JLabel();
        labelValorTotal = new javax.swing.JLabel();
        labelValorPrecio = new javax.swing.JLabel();
        labelValorImporte = new javax.swing.JLabel();
        botonLimpiar = new javax.swing.JButton();
        botonImprimir = new javax.swing.JButton();
        botonRegresar = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuDesplegable = new javax.swing.JMenu();
        menuDeplegableCliente = new javax.swing.JCheckBoxMenuItem();

        jLabel8.setText("PRECIO");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("ELECTRONICAS WU");

        labelProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelProducto.setText("PRODUCTO");

        labelCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelCantidad.setText("CANTIDAD");

        labelPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelPrecio.setText("PRECIO");

        labelImporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelImporte.setText("IMPORTE");

        botonAgregar.setBackground(new java.awt.Color(153, 255, 153));
        botonAgregar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        botonAgregar.setForeground(new java.awt.Color(0, 153, 51));
        botonAgregar.setText("+");
        botonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarActionPerformed(evt);
            }
        });

        spinnerCantidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        spinnerCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        spinnerCantidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinnerCantidadStateChanged(evt);
            }
        });

        comboBoxProducto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        comboBoxProducto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBoxProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxProductoActionPerformed(evt);
            }
        });

        tablaProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Producto", "Decripction", "Precio", "Cantidad", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaProductos);
        if (tablaProductos.getColumnModel().getColumnCount() > 0) {
            tablaProductos.getColumnModel().getColumn(0).setResizable(false);
        }

        labelIVA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelIVA.setText("IVA");

        labelSubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSubtotal.setText("SUBTOTAL");

        labelTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTotal.setText("TOTAL");

        labelValorSubtotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelValorSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelValorSubtotal.setText("$0.00 MXN");

        labelValorIVA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelValorIVA.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelValorIVA.setText("$0.00 MXN");

        labelValorTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelValorTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelValorTotal.setText("$0.00 MXN");

        labelValorPrecio.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelValorPrecio.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelValorPrecio.setText("$0.00 MXN");

        labelValorImporte.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelValorImporte.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelValorImporte.setText("$0.00 MXN");

        botonLimpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonLimpiar.setText("LIMPIAR");
        botonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonLimpiarMouseClicked(evt);
            }
        });

        botonImprimir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonImprimir.setText("IMPRIMIR");
        botonImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonImprimirActionPerformed(evt);
            }
        });

        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        menuDesplegable.setText("File");

        menuDeplegableCliente.setSelected(true);
        menuDeplegableCliente.setText("CLIENTE");
        menuDeplegableCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDeplegableClienteActionPerformed(evt);
            }
        });
        menuDesplegable.add(menuDeplegableCliente);

        jMenuBar1.add(menuDesplegable);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(217, 217, 217))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonImprimir)
                                .addGap(77, 77, 77)
                                .addComponent(botonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIVA)
                                    .addComponent(labelSubtotal)
                                    .addComponent(labelTotal))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelValorSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                    .addComponent(labelValorIVA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelProducto)
                            .addComponent(labelCantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecio)
                            .addComponent(labelImporte))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelValorPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(labelValorImporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelProducto)
                            .addComponent(labelPrecio)
                            .addComponent(comboBoxProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCantidad)
                            .addComponent(spinnerCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelValorPrecio)
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelValorImporte)
                                .addComponent(labelImporte)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelSubtotal)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelIVA)
                            .addComponent(labelValorIVA)))
                    .addComponent(labelValorSubtotal))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotal)
                    .addComponent(labelValorTotal))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonLimpiar)
                    .addComponent(botonImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonRegresar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboBoxProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxProductoActionPerformed
        calcularPrecio();
    }//GEN-LAST:event_comboBoxProductoActionPerformed

    private void spinnerCantidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerCantidadStateChanged
        calcularPrecio();
    }//GEN-LAST:event_spinnerCantidadStateChanged

    private void botonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarActionPerformed
        Producto producto = new Producto();
        producto.setIdProducto(comboBoxProducto.getSelectedIndex());
        producto.setDescripcion(comboBoxProducto.getSelectedItem().toString());
        producto.setPrecio(precio);
        producto.setCantidad(cantidad);
        producto.setImporte(precio*cantidad);
        if (!buscarProducto(producto)){
            listaProductos.add(producto); 
        }
        
        actualizarTabla();
        borrarVenta();
    }//GEN-LAST:event_botonAgregarActionPerformed

    private void botonLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonLimpiarMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) tablaProductos.getModel();
        model.setRowCount(0);
        labelValorSubtotal.setText("0");
        labelValorIVA.setText("0");
        labelValorTotal.setText("0");
        
        
    }//GEN-LAST:event_botonLimpiarMouseClicked

    private void botonImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonImprimirActionPerformed
        String archivoImpresion ="src/backupFilesTienda/Recibo cliente";
        File archivo = new File(archivoImpresion);
        try{
            FileWriter archivoEscrito = new FileWriter(archivo);
            BufferedWriter bw = new BufferedWriter(archivoEscrito);
            
             for(int i = 0; i < tablaProductos.getRowCount(); i++){//rows
                for(int j = 0; j < tablaProductos.getColumnCount(); j++){//columns
                    bw.write(tablaProductos.getValueAt(i, j).toString()+" ");
                }
                bw.newLine();
            }
            
            bw.close();
            archivoEscrito.close();
        
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonImprimirActionPerformed

    private void menuDeplegableClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDeplegableClienteActionPerformed
        frmCliente ClienteVenta = new frmCliente();
            ClienteVenta.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_menuDeplegableClienteActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
        frmMenu regresarMenu= new frmMenu();
        regresarMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed
    
    public boolean buscarProducto(Producto nuevo){
        for (Producto p : listaProductos){
            if(p.getIdProducto()==nuevo.getIdProducto()){
                int nuevaCantidad=p.getCantidad()+nuevo.getCantidad();
                p.setCantidad(nuevaCantidad);
                p.setImporte(p.getPrecio()*nuevaCantidad);
                return true;
            }
        }
        return false;
    }
    
    
    public void borrarVenta(){
        precio=0;
        cantidad=1;
        labelValorPrecio.setText(monetario(0));
        labelValorImporte.setText(monetario(0));
        comboBoxProducto.setSelectedIndex(0);
        spinnerCantidad.setValue(1);
        calcularPrecio();
        
    }
    
    public void calcularPrecio() {
        precio = metodosVenta.getPrecioProducto(comboBoxProducto.getSelectedIndex());
        cantidad=Integer.parseInt(spinnerCantidad.getValue().toString());
        labelValorPrecio.setText(monetario(precio));
        labelValorImporte.setText(monetario(precio*cantidad));
        
    }
    
    public String monetario(double precio){
        return "$ "+Math.round(precio*100.0)/100.0+" MXN";
    }
    
    public void actualizarTabla(){
        while(modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        double subtotal=0;
        for (Producto p : listaProductos){
            Object x[] = new Object[5];
            x[0] = p.getIdProducto();
            x[1] = p.getDescripcion();
            x[2] = monetario(p.getPrecio());
            x[3] = p.getCantidad();
            x[4] = monetario(p.getImporte());
            subtotal += p.getImporte();
            modelo.addRow(x);
                    
        }
        metodosVenta.calcularTotal(subtotal);
        
        labelValorSubtotal.setText(monetario(metodosVenta.getSubtotal()));
        labelValorIVA.setText(monetario(metodosVenta.getIVA()));
        labelValorTotal.setText(monetario(metodosVenta.getTotal()));
        tablaProductos.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregar;
    private javax.swing.JButton botonImprimir;
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JToggleButton botonRegresar;
    private javax.swing.JComboBox<String> comboBoxProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelIVA;
    private javax.swing.JLabel labelImporte;
    private javax.swing.JLabel labelPrecio;
    private javax.swing.JLabel labelProducto;
    private javax.swing.JLabel labelSubtotal;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelValorIVA;
    private javax.swing.JLabel labelValorImporte;
    private javax.swing.JLabel labelValorPrecio;
    private javax.swing.JLabel labelValorSubtotal;
    private javax.swing.JLabel labelValorTotal;
    private javax.swing.JCheckBoxMenuItem menuDeplegableCliente;
    private javax.swing.JMenu menuDesplegable;
    private javax.swing.JSpinner spinnerCantidad;
    private javax.swing.JTable tablaProductos;
    // End of variables declaration//GEN-END:variables
}
